config/routes.rb
Rails.application.routes.draw do
  resources :career_stages

  resources :mentor_industries

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, :controllers => { :omniauth_callbacks => 'omniauth_callbacks', :session => 'custom/devise/sessions' }, :skip => [:registrations]

  resources :users
  resources :mentorships, only: [:new, :create, :show, :destroy, :index]
  resources :locations, only: [:index, :show]

  get 'users/:id/will_participate' => 'users#participate', as: :participate
  get 'users/:id/will_not_participate' => 'users#not_participate', as: :not_participate

  root 'welcome#index'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                          :integer          not null, primary key
#  email                       :string(255)      default(""), not null
#  encrypted_password          :string(255)      default(""), not null
#  reset_password_token        :string(255)
#  reset_password_sent_at      :datetime
#  remember_created_at         :datetime
#  sign_in_count               :integer          default(0), not null
#  current_sign_in_at          :datetime
#  last_sign_in_at             :datetime
#  current_sign_in_ip          :inet
#  last_sign_in_ip             :inet
#  created_at                  :datetime
#  updated_at                  :datetime
#  provider                    :string(255)
#  uid                         :string(255)
#  first_name                  :string(255)
#  last_name                   :string(255)
#  mentor                      :boolean          default(FALSE)
#  primary_industry            :string(255)
#  stage_of_career             :integer
#  mentor_industry             :string(255)
#  peer_industry               :string(255)
#  current_goal                :string(255)
#  top_3_interests             :text             default([]), is an Array
#  waitlist                    :boolean          default(TRUE)
#  mentor_times                :integer          default(1)
#  mentor_limit                :integer          default(1)
#  is_participating_this_month :boolean
#  image_url                   :string(255)
#  location_id                 :integer
#  zip_code                    :string(10)
#  linkedin_url                :string(255)
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_location_id           (location_id)
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :omniauthable

  has_many :peer_group_users
  has_many :peer_groups, through: :peer_group_users
  belongs_to :location

  validates :top_3_interests, length: { maximum: 3, too_long: ' is limited to %{count} interests' }
  validates_presence_of :first_name, :last_name

  has_many :mentor_industry_users, dependent: :destroy
  has_many :mentor_industries, through: :mentor_industry_users
  accepts_nested_attributes_for :mentor_industry_users, allow_destroy: true

  after_validation :check_industry

  before_save :ensure_location_or_zip

  scope :mentors, -> { where(mentor: true) }
  scope :viewable_by, ->(user) { where(id: user.related_user_ids) }

  CURRENT_GOALS = [
    'Rising the ranks / breaking the glass ceiling',
    'Switching industries',
    'Finding work/life balance'
  ]

  PRIMARY_INDUSTRY = [
    'Business',
    'Technology',
    'Startup'
  ]

  TOP_3_INTERESTS = [
    'Arts',
    'Music',
    'Crafting',
    'Home improvement / Decorating',
    'Being a mom',
    'Dogs',
    'Cats',
    'Watching Sports',
    'Outdoors / Hiking',
    'Exercise',
    'Biking',
    'Yoga',
    'Running',
    'Beer',
    'Wine',
    'Traveling',
    'Local events',
    'Reading',
    'Photography',
    'Movies',
    'Cooking / Eating / Being a foodie',
    'Social issues / volunteering',
    'Video Games'
  ]

  def self.connect_to_linkedin(auth, signed_in_resource = nil)
    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first
    image_url = auth.extra.raw_info.pictureUrls.values[1][0] rescue nil
    linkedin_url = auth.extra.raw_info.publicProfileUrl
    if user
      user.update_attributes(image_url: image_url, linkedin_url: linkedin_url)
    else
      user = User.create(
        auth.info.slice(:first_name, :last_name, :email).merge(
          auth.slice(:provider, :uid)
        ).merge(
          image_url: image_url,
          linkedin_url: linkedin_url,
          password: Devise.friendly_token[0, 20]
        ).to_h
      )

      action = :new_user
      message = "#{user.id} is a new user"
      SlackNotification.notify(action, message)

      UserMailer.welcome_mail(user).deliver_now
    end
    return user
  end

  def self.match_peers_and_update_users
    # start
    action = :match_peers_and_update_users_start
    message = 'started update month'
    SlackNotification.notify(action, message)

    PeerGroup.generate_groups

    User.find_each do |user|
      if user.is_participating_this_month
        user.update(
          is_participating_this_month: false,
          mentor_times: user.mentor_limit
        )
      else
        user.update(mentor_times: 0)
      end
    end

    # finish
    action = :match_peers_and_update_users_finish
    message = 'finished update month'
    SlackNotification.notify(action, message)
  end

  def mentorships
    Mentorship.where('mentor_id = :user_id OR mentee_id = :user_id', user_id: id)
  end

  def check_industry
    if primary_industry == 'Other' || primary_industry == nil || peer_industry == nil || top_3_interests == [] || current_goal == nil
      self.waitlist = true
    else
      self.waitlist = false
    end
  end

  def mentor_limit= new_mentor_limit
    mentor_diff = new_mentor_limit.to_i - mentor_limit
    self.mentor_times = [mentor_times + mentor_diff, 0].max

    super
  end

  def get_image_url
    image_url ? image_url : 'icons/yello_person.png'
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def stage_of_career_name
    STAGE_OF_CAREER[stage_of_career - 1] rescue nil
  end

  def current_peer_group
    peer_groups.current.first
  end

  def peers
    if current_peer_group
      current_peer_group.users - [self]
    else
      []
    end
  end

  def my_mentors
    Mentorship.mentoring(self).all.map(&:mentor_id).compact
  end

  def my_mentees
    Mentorship.mentored_by(self).all.map(&:mentee_id).compact
  end

  def related_user_ids
    [id, peers.map(&:id), my_mentors, my_mentees].flatten
  end

  private

  def ensure_location_or_zip
    self.zip_code = nil if location_id
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :auth_user
  before_action :set_industries_and_interests, only: [:edit, :update]

  def show
    permitted_users = User.where(id: current_user.related_user_ids)
    @user = permitted_users.find(params[:id])
    @career_stages = MentorIndustryUser.career_stages
    @mentee_mentorships = Mentorship.mentored_by(@user).order(:created_at).last(3)
    @mentor_mentorships = Mentorship.mentoring(@user).order(:created_at).last(3)
  end

  def edit
    @user = current_user
    @industries = MentorIndustry.all
    @interests = User::TOP_3_INTERESTS
    @career_stages = MentorIndustryUser.career_stages

    MentorIndustry.all.each do |industry|
      if !@user.mentor_industry_ids.include?(industry.id)
        @user.mentor_industry_users.build(mentor_industry_id: industry.id)
      end
    end
  end

  def update
    @user = current_user

    if @user.update(user_params)
      redirect_to user_path(current_user)
    else
      @industries = MentorIndustry.all
      @interests = User::TOP_3_INTERESTS
      @career_stages = MentorIndustryUser.career_stages

      MentorIndustry.all.each do |industry|
        if !@user.mentor_industry_ids.include?(industry.id)
          @user.mentor_industry_users.build(mentor_industry_id: industry.id)
        end
      end

      render 'edit'
    end
  end

  def participate
    @user = current_user
    @user.update(is_participating_this_month: true)

    action = :user_participating
    message = "User id #{@user.id} is participating in #{@user.location.name}"
    SlackNotification.notify(action, message)

    redirect_to user_path(current_user)
  end

  def not_participate
    @user = current_user
    @user.update(is_participating_this_month: false)

    redirect_to user_path(current_user)
  end

  private

  def set_industries_and_interests
    @industries = User::PRIMARY_INDUSTRY
    @interests = User::TOP_3_INTERESTS
  end

  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :email,
      :mentor,
      :mentor_limit,
      :primary_industry,
      :stage_of_career,
      :peer_industry,
      :current_goal,
      :location_id,
      :zip_code,
      {
        mentor_industry_users_attributes: [
          :name,
          :career_stage,
          :_destroy,
          :id,
          :mentor_industry_id
        ]
      },
      top_3_interests: []
    )
  end

  def policy_scope scope
    scope.viewable_by(current_user)
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<br>
<br>
<br>
<%= form_for @user do |f| %>
  <% if @user.errors.messages.any? %>
    <% @user.errors.full_messages.each do |message| %>
      <div class="alert alert-danger" role="alert"><%= message %></div>
    <%end%>
  <%end%>

  <aside class="col-md-3 side-divider">
    <%= image_tag(@user.get_image_url, class: "profile") %>
    <div class="large-frame">
      <h3><%= @user.first_name%> <%= @user.last_name %></h3>
    </div>
  </aside>

  <main>
    <div class="blog-main">
      <section class="mentor divider col-md-9">
        <h1 class="subject no-frame">Edit Your Profile</h1>
        <br>
        <% if @user.waitlist%>
          <h2 class="no-frame">Status: <span>Waitlisted</span></h2>
          <p class="tiny-frame">Either because you made your primary career 'Other' (which we currently don't support yet) or you did not finish your profile</p>
        <%end%>
      </section>
      <h2 class="col-md-9">Info</h2>
      <section class="context col-md-6">
        <div class="row flush medium-frame form-group">
          <h4>First Name</h4>
          <%= f.text_field :first_name, class: 'form-control' %>
          <h4>Last Name</h4>
          <%= f.text_field :last_name, class: 'form-control' %>
          <h4>Email</h4>
          <%= f.text_field :email, class: 'form-control' %>
          <h4>Location</h4>
          <h4 class="form-group" id="gray-text"><%= f.collection_select(:location_id, Location.all, :id, :city_state, include_blank: 'Other') %></h4>
          <h4 class="medium-frame hidden" id="zip-code">Zip Code:
            <div class="form-group">
              <%= f.number_field :zip_code, class: 'form-control' %>
              <p>
                You will not be placed in a peer group and can only mentor.
                However, we're working hard to expand Women Rising to other areas.
                Enter your zip code to let us know where you want a Women Rising chapter.
              </p>
            </div>
          </h4>
          <h4>Primary Industry</h4>
          <h4 id="gray-text">
            <% @industries.each do |industry| %>
              <%= f.radio_button :primary_industry, industry.name.humanize %>
              <%= f.label :industry, industry.name.humanize, :value => industry%>
            <%end%>
            <%= f.radio_button :primary_industry, "Other"%>
            <%= f.label :Other, "Other".humanize, :value => "Other"%>
          </h4>
          <h4>Current Goal</h4>
          <h4 id="gray-text"><%= f.select :current_goal, options_for_select(User::CURRENT_GOALS, @user.current_goal)%></h4>
          <h4 id="gray-text">NOTE TO THOSE WORKING IN STARTUPS: Rate your stage of career more on experience level than position title. For example, if you're just starting out in your new company, being a CEO is probably equivalent to management level, not CEO level.</h4>
          <h4>Stage of Career</h4>
          <h4 id="gray-text"><%= f.select :stage_of_career, options_for_select(@career_stages, @user.stage_of_career), class: "form-control" %></h4>
          <h4>I want to find peers in this industry</h4>
          <h4 id="gray-text"><% @industries.each do |industry| %>
            <%= f.radio_button :peer_industry, industry.name%>
            <%= f.label :industry, industry.name.humanize, :value => industry%>
          <%end%></h4>
          <h4>Would you like to be a mentor? <span id="gray-text"><%= f.select :mentor, options_for_select([["Yes",true],["No",false]], @user.mentor), { :class => 'mentor' } %></span></h4>
          <h4 id="mentor-info gray-text">
            <%= f.fields_for :mentor_industry_users, @user.mentor_industry_users do |f| %>
              <%= f.hidden_field :mentor_industry_id %>
              <div class="mentor_check_box"><%= f.check_box :_destroy, {checked: f.object.id?}, '0', '1' %> <%= f.label :_destroy, f.object.name %></div>
              <div class="mentor_career_stage"><%= f.collection_select :career_stage, @career_stages.keys, :to_s, :to_s %></div>
            <% end %>
            <br>
            <%= f.label :How_many_times_would_you_like_to_mentor_per_month?%>
            <%= f.number_field :mentor_limit, in: 0..10%></br>
          </h4>
        </div>
      </section>
      <section class="edit col-md-3">
        <div class="medium-frame form-group">
          <h4>Top 3 Non-Career Interests</h4>
          <p id="gray-text">
            <% @interests.each_with_index do |interest,index| %>
              <% if (index + 1) % 3 == 0 %>
                <div><%= check_box_tag 'user[top_3_interests][]', interest, @user.top_3_interests.include?(interest) %>
                <%= f.label :interest, interest.humanize, :value => interest, class:"check"%></div></br>
              <%else%>
                <div><%= check_box_tag 'user[top_3_interests][]', interest, @user.top_3_interests.include?(interest) %>
                <%= f.label :interest, interest.humanize, :value => interest, class:"check"%></div>
              <%end%>
            <%end%>
          </p>
        </div>
        <p>PS -- we'd love if you told some friends or tweeted something like "I just joined @TheWomenRising, an awesome new network for women to connect, support and mentor each other! http://www.womenrising.co"</p>
        <%= f.submit "Submit", class:"btn medium-frame"%>
      </section>
    </div>
  </main>
<%end%>

<script>
  $(function() {
    $('#user_location_id').on('change', function() {
      $('#zip-code').toggleClass("hidden", $(this).val() !== "");
    }).trigger('change');
  });
</script>

app/views/users/show.html.erb
<br>
<br>
<br>

<aside class="col-md-3 col-md-offset-1 side-divider">
  <%= image_tag(@user.get_image_url, class: "profile") %>
  <div class="large-frame">
    <h2><%= @user.full_name %></h2>
  </div>

  <% if @user == current_user && @mentor_mentorships.present? %>
    <h4>Your Mentors</h4>
    <ul class="mentor-list">
      <% @mentor_mentorships.each do |mentorship| %>
        <li title="<%= mentorship.question %>">
          <%= image_tag mentorship.mentor.get_image_url rescue content_tag(:div, nil, class: 'profile-placeholder') %>
          <p>
            &quot;<%= truncate(mentorship.question) %>&quot;
            <br>
            <% if mentorship.mentor %>
              <a href="<%= user_path mentorship.mentor %>">
                <%= mentorship.mentor.full_name %>
              </a>
            <% else %>
              <em>Pending</em>
              <%= link_to "Cancel", mentorship_path(mentorship), method: :delete %></br>
            <% end %>
          </p>
        </li>
      <% end %>
    </ul>
  <% end %>

  <% if @user == current_user && @mentee_mentorships.present? %>
    <h4>Your Mentees</h4>
    <ul class="mentor-list">
      <% @mentee_mentorships.each do |mentorship| %>
        <li>
          <%= image_tag mentorship.mentee.get_image_url %>
          <p>
            &quot;<%= truncate(mentorship.question) %>&quot;
            <br>
            <a href="<%= user_path mentorship.mentee %>">
              <%= mentorship.mentee.full_name %>
            </a>
          </p>
        </li>
      <% end %>
    </ul>
  <% end %>

  <% if @user == current_user %>
    <div>
      <%= link_to "Mentorship History", mentorships_path, class: 'btn medium-frame btn-secondary' %>
    </div>
  <% end %>

  <% if @user.peers.any? %>
    <h4><%= @user == current_user ? 'Your' : '' %> Peers This Month</h4>
    <ul class="profile-list">
      <% @user.peers.each do |peer| %>
        <li>
          <a href="<%= user_path peer %>">
            <%= image_tag peer.get_image_url %>
            <h5><%= peer.full_name %></h5>
          </a>
        </li>
      <% end %>
    </ul>
  <% end %>
</aside>

<main class="col-md-8 side-frame container-fluid">
  <div class="blog-main">
    <div class="row">
      <% if @user == current_user %>
        <section class="actions">
          <div class="col-md-7">
            <h3 class="subject no-frame">Will you participate in peer matches this month?</h3>
            <h4 class="participating"><%= @user.is_participating_this_month ? "YES" : "NO"%>&nbsp;
              <% if !@user.is_participating_this_month %>
                <%= link_to "Click to participate this month", participate_path(@user), class: "btn medium-frame"%></br>
              <% else %>
                <%= link_to "Click to not participate this month", not_participate_path(@user), class: "btn medium-frame"%></br>
              <% end %>
            </h4>
          </div>
          <div class="col-md-5">
            <h3 class="subject no-frame">Request A Mentor</h3>
            <%= link_to "Request a Mentor", new_mentorship_path, class: "btn", id: "mentor-button" %>
          </div>
        </section>
        <% if @user.waitlist%>
          <section class="waitlist large-frame">
            <h2 class="no-frame">Status: <span>Waitlisted</span></h2>
            <p class="tiny-frame">Either because you made your primary career 'Other' (which we currently don't support yet) or you did not finish your profile</p>
          </section>
        <% end %>
      <% end %>
    </div>
    <section class="context">
      <h2>Info</h2>
      <div class="row flush">
        <div class="col-md-6 flush">
          <h4 class="medium-frame">Location: <div><%= @user.location.city_state rescue 'N/A' %></div></h4>
          <h4 class="medium-frame">Primary Industry: <div><%= @user.primary_industry%></div></h4>
          <h4 class="medium-frame">Goal Right Now: <div><%= @user.current_goal%></div></h4>
          <div class="medium-frame">
            <h4 class="no-frame">My Top 3 non-career interests are: </h4>
            <ul>
              <% @user.top_3_interests.each do |interest|%>
                <li><h4 id="gray-text"><%= interest%></h4></li>
              <% end %>
            </ul>
          </div>
        </div>
        <div class="col-md-6">
          <h4 class="medium-frame">Email: <div><%= @user.email%></div></h4>
          <h4 class="medium-frame">Stage Of Career: <div><%= @career_stages.key(@user.stage_of_career) %></div>
          </h4>
          <h4 class="medium-frame">I want to find peers in this industry: <div><%= @user.peer_industry%></div></h4>
          <% if @user.mentor == true %>
            <h4 class="medium-frame">Industries I will mentor in:
              <% @user.mentor_industry_users.each do |miu| %>
                <ul>
                  <li>
                    <div><strong><%= miu.name %></strong> as a <%= miu.career_stage %> in the industry.</div>
                  </li>
                </ul>
              <% end %>
            </h4>
          <% end %>
        </div>
      </div>
    </section>
    <% if @user == current_user %>
      <section class="edit">
        <%= link_to "Edit My Profile", edit_user_path(@user), class: "btn medium-frame" %>
      </section>
    <% end %>
  </div>
</main>
</div>